book_center/book_center/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_center.bc_main.urls')),
    path('auth/', include('book_center.bc_auth.urls')),
    path('contact/', include('book_center.bc_contact.urls')),
    path('events/', include('book_center.bc_events.urls')),
    path('profiles/', include('book_center.bc_profiles.urls')),
    path('blog/', include('book_center.bc_blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_center/book_center/bc_profiles/models/discussions.py
from book_center.bc_auth.models import BookCenterUser
from book_center.utils.validators import validate_alphabet_characters_english
from django.core.validators import MinLengthValidator
from django.db import models


class BookCenterDiscussion(models.Model):
    title = models.CharField(
        max_length=50,
        validators=(
            validate_alphabet_characters_english,
            MinLengthValidator(5),
        )
    )

    description = models.CharField(
        max_length=200,
        validators=(
            validate_alphabet_characters_english,
            MinLengthValidator(10),
        )
    )

    topic = models.CharField(
        max_length=20,
        validators=(
            validate_alphabet_characters_english,
        )
    )

    author = models.ForeignKey(
        BookCenterUser,
        on_delete=models.CASCADE,
        null=True
    )

    created_on = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = ['created_on']
        verbose_name = 'Discussion'

    def __str__(self):
        return self.title


class BookCenterDiscussionComment(models.Model):
    comment = models.CharField(
        max_length=500,
        validators=(
            validate_alphabet_characters_english,
        )
    )

    discussion = models.ForeignKey(
        BookCenterDiscussion,
        on_delete=models.CASCADE,
        null=True
    )

    author = models.ForeignKey(
        BookCenterUser,
        on_delete=models.CASCADE,
        null=True
    )

    like = models.BooleanField(
        default=False
    )
    dislike = models.BooleanField(
        default=False
    )

    created_on = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        ordering = ['created_on']
        verbose_name = 'Comment'


class BookCenterDiscussionLike(models.Model):
    discussion = models.ForeignKey(
        BookCenterDiscussion,
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        BookCenterUser,
        on_delete=models.CASCADE
    )


class CommentUpvote(models.Model):
    comment = models.ForeignKey(
        BookCenterDiscussionComment,
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        BookCenterUser,
        on_delete=models.CASCADE
    )

book_center/book_center/bc_profiles/models/profiles.py
from book_center.bc_auth.models import BookCenterUser
from book_center.utils.validators import validate_alphabet_characters_english
from django.db import models

SUPPORTED_COUNTRIES = [
    ('BG', 'Bulgaria'),
    ('UK', 'United Kingdom'),
    ('RO', 'Romania'),
]


class BookCenterUserProfile(models.Model):
    first_name = models.CharField(
        max_length=20,
        blank=True,
        validators=(
            validate_alphabet_characters_english,
        )
    )

    last_name = models.CharField(
        max_length=20,
        blank=True,
        validators=(
            validate_alphabet_characters_english,
        )
    )

    bio = models.CharField(
        max_length=200,
        blank=True,
        validators=(
            validate_alphabet_characters_english,
        ),
    )

    profile_image = models.ImageField(
        upload_to='profiles',
        default='profiles/default_profile_img.jpg'
    )

    country = models.CharField(
        max_length=100,
        choices=SUPPORTED_COUNTRIES,
        blank=True,
    )

    city = models.CharField(
        max_length=50,
        blank=True,
        validators=(
            validate_alphabet_characters_english,
        )
    )

    twitter_account = models.CharField(
        max_length=50,
        blank=True,
        validators=(
            validate_alphabet_characters_english,
        )
    )

    facebook_account = models.CharField(
        max_length=50,
        blank=True,
        validators=(
            validate_alphabet_characters_english,
        )
    )

    instagram_account = models.CharField(
        max_length=50,
        blank=True,
        validators=(
            validate_alphabet_characters_english,
        )
    )

    user = models.OneToOneField(BookCenterUser, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Profile'

book_center/book_center/bc_profiles/forms/discussions.py
from book_center.bc_profiles.models.discussions import BookCenterDiscussion, BookCenterDiscussionComment
from book_center.utils.mixins import DisableAutocompleteMixin
from django import forms


class DiscussionForm(DisableAutocompleteMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap()

    class Meta:
        model = BookCenterDiscussion
        exclude = ('author',)

    description = forms.CharField(
        max_length=200,
        widget=forms.Textarea()
    )

    created_on = forms.DateTimeField(
        widget=forms.TextInput(
            attrs={
                'readonly': 'readonly'
            }
        ),
        required=False,
    )


class DiscussionCommentForm(DisableAutocompleteMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap()

    class Meta:
        model = BookCenterDiscussionComment
        fields = ('comment', )

    comment = forms.CharField(
        max_length=500,
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Leave a comment',
                'rows': 3,
            }
        ),
    )

book_center/book_center/bc_profiles/forms/profiles.py
from book_center.bc_profiles.models.profiles import BookCenterUserProfile
from book_center.utils.mixins import DisableAutocompleteMixin, NoLabelFormMixin
from book_center.utils.validators import validate_alphabet_characters_english
from django.contrib.auth.forms import PasswordChangeForm
from django.core.validators import MinLengthValidator
from django import forms


class UserProfileForm(DisableAutocompleteMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap()

    class Meta:
        model = BookCenterUserProfile
        exclude = ('user', )

    bio = forms.CharField(
        max_length=200,
        required=False,
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Tell us a few words about yourself',

            }
        )
    )


class ChangePasswordForm(NoLabelFormMixin, PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap()

    old_password = forms.CharField(
        max_length=20,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Enter your current password*'}
        ),
    )

    new_password1 = forms.CharField(
        max_length=20,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Enter your new password*'}
        ),
        validators=(
            validate_alphabet_characters_english,
            MinLengthValidator(5)
        )
    )

    new_password2 = forms.CharField(
        max_length=20,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Confirm your new password*'}
        ),
    )

book_center/book_center/bc_profiles/views/discussions.py
from book_center.bc_profiles.models.discussions import BookCenterDiscussion, BookCenterDiscussionComment, BookCenterDiscussionLike
from book_center.bc_profiles.forms.discussions import DiscussionForm, DiscussionCommentForm
from django.views.generic import DeleteView, UpdateView, CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View


def save_comment(form, discussion, user):
    comment = form.save(commit=False)
    comment.discussion = discussion
    comment.author = user
    comment.save()


class AllDiscussionsView(LoginRequiredMixin, ListView):
    template_name = 'profiles/discussions/discussions.html'
    context_object_name = 'discussions'
    model = BookCenterDiscussion


@login_required()
def discussion_details_view(request, pk):
    discussion = get_object_or_404(BookCenterDiscussion, pk=pk)
    comments = BookCenterDiscussionComment.objects.filter(discussion=pk)
    is_liked_by_user = discussion.bookcenterdiscussionlike_set.filter(user_id=request.user.id).exists()

    if request.method == 'POST':
        comment_form = DiscussionCommentForm(request.POST)

        if comment_form.is_valid():
            save_comment(comment_form, discussion, request.user)
            return redirect('discussion details', discussion.id)

    context = {
        'discussion': discussion,
        'comment': DiscussionCommentForm(),
        'all_comments': comments,
        'is_liked': is_liked_by_user,
    }
    return render(request, 'profiles/discussions/discussion_details.html', context)


class CreateDiscussionView(LoginRequiredMixin, CreateView):
    template_name = 'profiles/discussions/create_discussion.html'
    model = BookCenterDiscussion
    form_class = DiscussionForm
    success_url = reverse_lazy('show all discussions')

    def form_valid(self, form):
        discussion = form.save(commit=False)
        discussion.author = self.request.user
        discussion.save()
        return super().form_valid(form)


class EditDiscussionView(LoginRequiredMixin, UpdateView):
    template_name = 'profiles/discussions/edit_discussion.html'
    model = BookCenterDiscussion
    form_class = DiscussionForm
    success_url = reverse_lazy('show all discussions')


class DeleteDiscussionView(LoginRequiredMixin, DeleteView):
    template_name = 'profiles/discussions/delete_discussion.html'
    model = BookCenterDiscussion
    success_url = reverse_lazy('show all discussions')


class LikeCommentView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        discussion = BookCenterDiscussion.objects.get(pk=self.kwargs['pk'])
        like_object_by_user = discussion.discussionlike_set.filter(user_id=self.request.user.id).first()

        if not like_object_by_user:
            like = BookCenterDiscussionLike(
                discussion=discussion,
                user=self.request.user,
            )
            like.save()

        return redirect('discussion details', discussion.id)


@login_required()
def delete_comment_view(request, pk, comment_id):
    comment = BookCenterDiscussionComment.objects.get(pk=comment_id)
    comment.delete()
    return redirect('discussion details', pk)

book_center/book_center/bc_profiles/views/profiles.py
from book_center.bc_auth.models import BookCenterUser
from book_center.bc_profiles.models.profiles import BookCenterUserProfile
from book_center.bc_profiles.forms.profiles import ChangePasswordForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.views.generic import TemplateView


class ProfileMainView(LoginRequiredMixin, TemplateView):
    template_name = 'profiles/profiles/profile_main.html'
    pk_url_kwarg = "username"


class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'profiles/profiles/change_password.html'
    form_class = ChangePasswordForm
    pk_url_kwarg = "username"
    success_url = reverse_lazy('reset password complete')


@login_required()
def edit_profile_view(request, username):
    user = BookCenterUser.objects.get(username=username)
    profile = BookCenterUserProfile.objects.get(user_id=user.id)
    form = UserProfileForm(instance=profile)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile main', username)

    context = {
        'form': form,
        'profile': profile,

    }
    return render(request, 'profiles/profiles/edit_profile_details.html', context)

book_center/templates/profiles/discussions/create_discussion.html
{% extends 'profiles/main/base.html' %}
{% load crispy_forms_tags %}

{% block title%}
    New Discussion
{% endblock %}


{% block content %}
     <div class="row">
            <div class="col-md-8">
                <div style="width: 500px" class="card">
                    <div class="card-body">
                        <form action="{% url 'create discussion' %}" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button class="btn btn-primary">Create</button>
                        </form>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
    </div>
{% endblock %}

book_center/templates/profiles/discussions/delete_discussion.html
{% extends 'profiles/main/base.html' %}

{% block title %}
    Delete Discussion
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete this discussion?</h1>
            <div class="m-auto d-flex justify-content-center">
                <div class="m-2">
                    <form method="post">
                        {% csrf_token %}
                        <input type="submit" value="Confirm" class="btn btn-danger"/>
                    </form>
                </div>
                <div class="m-2">
                    <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

book_center/templates/profiles/discussions/discussion_details.html
{% extends 'profiles/main/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    View Discussion
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <div style="width: 500px" class="card">
                <div class="card-body">
                    <h1><a style=""> {{ discussion.title }}</a></h1>
                    <h5>Topic: <a style="color: grey">{{ discussion.topic }}</a> Author: <a
                            style="color: gray">{{ discussion.author }}</a></h5>
                    <p style="margin-top: 15px">{{ discussion.description }}</p>
                    <hr>
                    {% if user.id == discussion.author.id %}
                        <p><a href="{% url 'edit discussion' discussion.id %}"
                              style="margin-top: 15px; width: 190px"
                              class="btn btn-primary">Edit Discussion</a>
                            <a href="{% url 'delete discussion' discussion.id %}"
                               style="margin-top: 15px; width: 190px"
                               class="btn btn-danger">Delete</a>
                        </p>
                    {% else %}
                        {% if is_liked %}
                            <a style="font-size: 11px" href="">You have already liked this discussion.</a>
                        {% else %}
                            <a href="{% url 'like comment' discussion.id %}" style="font-size: 11px">Do you like this
                            discussion? Give it a
                            <i style="font-size: 15px" class="fa fa-thumbs-up" aria-hidden="true"></i>
                        {% endif %}
                    {% endif %}
                    <hr>
                    <form style="" method="post">
                        {% csrf_token %}
                        <div style="">
                            {{ comment|crispy }}
                        </div>
                        <button class="btn-primary">Publish</button>
                    </form>

                    <hr>
                    {% for comment in all_comments %}

                        <h5>{{ comment.comment }}</h5>
                        <p style="font-size: 9px" class="text-info">
                            posted {{ comment.created_on }} by {{ comment.author }}
                        </p>
                        {% if comment.author == request.user %}
                            <button style="font-size: 11px; width: auto; margin-top: 12px" class="btn-danger">
                                <a style="color: whitesmoke" href="{% url 'delete comment' discussion.id comment.id %}">
                                    Delete
                                </a>
                            </button>
                        {% endif %}
                        <hr>
                    {% endfor %}
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

book_center/templates/profiles/discussions/discussions.html
{% extends 'profiles/main/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Discussions
{% endblock %}

{% block content %}
<a href="{% url 'create discussion' %}" class="btn btn-primary" style="margin-bottom: 17px">
    Add New Discussion
</a>
    <div class="row">
        {% for d in discussions %}
            <div class="col-md-8">
                <div style="width: 400px" class="card">
                    <div class="card-body">
                        <h4><a style="" href="{% url 'discussion details' d.id %}"> {{ d.title }}</a></h4>
                        <p>Topic: {{ d.topic }}</p>
                        <p>Author: {{ d.author }}</p>
                        <hr>
                        <p style="font-size: 10px" class="text-white">{{ d.bookcenterdiscussioncomment_set.count }} Comments</p>
                        <p style="font-size: 10px" class="text-white">{{ d.bookcenterdiscussionlike_set.count}} Likes</p>
                        <p style="font-size: 9px" class="text-info">
                            posted {{d.created_on}} by {{ d.author }}
                        </p>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

book_center/templates/profiles/discussions/edit_discussion.html
{% extends 'profiles/main/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Edit Discussion
{% endblock %}

{% block content %}
            <div class="row">
            <div class="col-md-8">
                <div style="width: 500px" class="card">
                    <div class="card-body">
                      <form method="post">
                          {% csrf_token %}
                          {{ form|crispy }}
                          <button class="btn btn-primary">Update Discussion</button>
                      </form>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
    </div>
{% endblock %}